from __future__ import annotations


UDP_DEBUG_LISTEN_IP = "0.0.0.0"
UDP_DEBUG_LOOPBACK_IP = "127.0.0.1"

#RSA_DEFAULT_PORT = 50002
#PVD_DEFAULT_PORT = 50001
RSA_DEFAULT_PORT = 16002
PVD_DEFAULT_PORT = 16001

RSA_DEFAULT_TARGET = (UDP_DEBUG_LOOPBACK_IP, RSA_DEFAULT_PORT)
PVD_DEFAULT_TARGET = (UDP_DEBUG_LOOPBACK_IP, PVD_DEFAULT_PORT)

DEFAULT_PARSE_BUFSIZE = 65000
DEFAULT_BYPASS_BUFSIZE = 65535

RSA_WATCH_VEHICLE_IDS: list[int] = [62569]
RSA_OUTPUT_MODE = "all"  # "all" or "watch_only"
